function outs = ba_media_types(MediaName)
% Media Name, Viscosity_Pas, Components, Component_Concentration, Component_Units

a(1) = AdhesionMediaDataF("Int25k", 0.014, ...
                                     ["Lactose", "Galactose", "GalNAc", "GlcNac", "Sialic Acid", "PEG20k"], ...
                                     [0.0365, 0.0365, 0.0365, 0.0365, 0.0365, 0.1], ...
                                     ["mol/L", "mol/L", "mol/L", "mol/L", "mol/L", "mass fraction"]);

a(2) = AdhesionMediaDataF("IntNANA", 0.012, ...
                                       ["Sialic Acid", "PEG20k"], ...
                                       [0.0365, 0.1], ...
                                       ["mol/L", "mass fraction"]);

a(3) = AdhesionMediaDataF("IntGlcNAc", 0.0118, ...
                                           ["GlcNac", "PEG20k"], ...
                                           [0.0365, 0.1], ...
                                           ["mol/L", "mass fraction"]);                          

a(4) = AdhesionMediaDataF("IntGalNAc", 0.0118, ...
                                           ["GalNac", "PEG20k"], ...
                                           [0.0365, 0.1], ...
                                           ["mol/L", "mass fraction"]);  

a(5) = AdhesionMediaDataF("NoInt", 0.0115, ...
                                   "PEG20k", ...
                                   0.1, ...
                                   "mass fraction");  


a(6) = AdhesionMediaDataF("NoInt20", 0.0569, ...
                                   "PEG20k", ...
                                   0.2, ...
                                   "mass fraction");  

a(7) = AdhesionMediaDataF("IntGalactose", 0.012, ...
                                           ["Galactose", "PEG20k"], ...
                                           [0.0365, 0.1], ...
                                           ["mol/L", "mass fraction"]);                          
                                       
a(8) = AdhesionMediaDataF("IntNP40", 0.0117, ...
                                   ["NP-40", "PEG20k"], ...
                                   [0.1, 0.1], ...
                                   ["percent", "mass fraction"]);  

a(9) = AdhesionMediaDataF("Int25knormpH", 0.014, ...
                                     ["Lactose", "Galactose", "GalNAc", "GlcNac", "Sialic Acid", "PEG20k"], ...
                                     [0.0365, 0.0365, 0.0365, 0.0365, 0.0365, 0.1], ...
                                     ["mol/L", "mol/L", "mol/L", "mol/L", "mol/L", "mass fraction"]);
                                 
a(10) = AdhesionMediaDataF("Int", 0.014, ...
                                     ["Lactose", "Galactose", "GalNAc", "GlcNac", "Sialic Acid", "PEG20k"], ...
                                     [0.0365, 0.0365, 0.0365, 0.0365, 0.0365, 0.1], ...
                                     ["mol/L", "mol/L", "mol/L", "mol/L", "mol/L", "mass fraction"]);

a(11) = AdhesionMediaDataF("Int5xPBS", 0.0127, ...
                                     ["Lactose", "Galactose", "GalNAc", "GlcNac", "Sialic Acid", "PEG20k"], ...
                                     [0, 0, 0, 0, 0, 0.1], ...
                                     ["mol/L", "mol/L", "mol/L", "mol/L", "mol/L", "mass fraction"]);

                               
MediaTable = struct2table(a);
MediaTable.Properties.RowNames = lower(MediaTable.Name);

if nargin < 1 || isempty(MediaName)
    outs = MediaTable;
elseif nargin > 1
    error('Too many input arguments.');
else
    outs = table2struct(MediaTable(MediaName,:));
end       

end


function outs = AdhesionMediaDataF(Media_Name, Viscosity_Pas, Components, Component_Conc, Component_Units)
    outs.Name = Media_Name;
    % outs.ManufactureData = [];
    outs.Viscosity = Viscosity_Pas;
    outs.Components = table(Components(:), Component_Conc(:), Component_Units(:), 'VariableNames', {'Name', 'Conc', 'ConcUnits'});
end