%Function Generates a Table of Bead Images and Associated Data for the MP4
%videos in the current directory using Cellfun functions and data generated by generatedata; make sure the path currently linked to
%the workspace is the path in which 

%NOTE: Must be used in after generatedata() has been called

function [GeneratedTable] = generatetable(folder,name,frames,images)

[centers, radii] = cellfun(@(x1)imfindcircles(x1,[8 30]),images,'UniformOutput',false);
BeadNumber = cell2mat(cellfun(@numel,radii,'UniformOutput',false));
NearestNeighborDist = cellfun(@nndist,centers,'UniformOutput',false);
MeanDist = cell2mat(cellfun(@(x1)mean(x1,'omitnan'),NearestNeighborDist,'UniformOutput',false));
MinimumDist = cellfun(@(x1)min(x1,[],'omitnan'),NearestNeighborDist,'UniformOutput',false);
MedianDist = cell2mat(cellfun(@(x1)median(x1,[],'omitnan'),NearestNeighborDist,'UniformOutput',false));
%NearestNeighborDist = cell2mat(cellfun(@nndist,centers,'UniformOutput',false));


GeneratedTable = table(folder,name,frames,images,centers,radii,BeadNumber,NearestNeighborDist,MinimumDist,MeanDist,MedianDist);