function platedef = ba_read_plate_layout(filename)
% BA_READ_PLATE_LAYOUT Import metadata from Well_Layout for 15-well plate.
%
% 

% Auto-generated by MATLAB on 2018/06/05 13:40:44

%-- Initialize variables.
delimiter = ',';
startRow = 2;
endRow = inf;

%-- Format for each line of text:
formatSpec = '%C%C%f%f%s%s%s%[^\n\r]';

%-- Open the text file.
fileID = fopen(filename,'r');

%-- Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%-- Close the text file.
fclose(fileID);

%-- Create output variable
platedef = table(dataArray{1:end-1}, 'VariableNames', {'PlateRow','PlateColumn','Well_ID','ObjectID','ObjectName','FieldName','Value'});
platedef.ObjectName = cellstr(platedef.ObjectName);
platedef.FieldName = cellstr(platedef.FieldName);
platedef.Value = cellstr(platedef.Value);
platedef = movevars(platedef, {'PlateRow','PlateColumn','ObjectID','ObjectName','FieldName','Value'}, 'after', 'Well_ID');

%-- Convert old 96-well IDs to new 15-well IDs (delete rows > C, columns > 5)

% Compatible 96-well IDs for the new 15-well plate definition
compat96well_IDs(:,1) = [1:5,13:17,25:29];

% Pull out the good 96-well IDs that apply to the 15-well Adhesion Assay
% platedef. The second output returns the index location, which is,
% conveniently, equal to our new Well_IDs for the 15-well plate. Any Well_ID
% under the old 96-well spec that doesn't work for the 15-well spec is 
% zeroed out and is removed simply by filtering for where the new 
% Well_IDs are greater than zero.
[~, newWell_IDs] = ismember(platedef.Well_ID, compat96well_IDs);
platedef.Well_ID = newWell_IDs;
platedef = platedef( platedef.Well_ID > 0, :);


